DelNov/T-Flows

- Sources/Process/Update_Boundary_Values.f90
- Tests/Rans/Fuel_Bundle/convert.scr
Returned line 240 of Sources/Process/Update_Boundary_Values.f90
in previous state:
`eps % n(c2) = eps % n(grid % bnd_cond % copy_c(c2))`
as was suggested by Muhamed in 
> Egor, this is not supposed to be done in Sources. This copy  boundary is when you have axillary domains that you use to generate  inflow boundary condition, mainly for LES. It needs to update boundary  every time step, and it should stay in Update_Boundary_Values.f90.
> Returned line 240 of Sources/Process/Update_Boundary_Values.f90

- Sources/Process/Main_Pro.f90
The trouble was that more than one processors were trying to delete file "exit_now".  I restricted this action to one processor only.
> Resolved issue #12 (Program sometimes crashes if it runs in parallel, and "exit_now" is created.)

- Sources/Process/Load_Backup.f90
- Sources/Process/Save_Backup.f90
This was not implemented in the code at all.  In the correction, I assume that the number of materials is 1 - which is the case for this release, we agreed we will re-implement multiple materials in a better way in the future.
> Resolved issue #6: bulk fluxes and pressure drops not saved in backup.

- Sources/Process/Load_Backup.f90
- Sources/Process/Save_Backup.f90
- Sources/Process/Update_Boundary_Values.f90
Dear guys,
Here is the fix - please check if other turbulent quantities have to be saved with RSM models.  Check lines 142 and 146 in Load_Backup.f90 and Save_Backup.f90 to see what I am talking about.
> Issue #16 (BUG) Reynolds stresses not save in backup files

- Tests/Rans/Channel_Re_Tau_590/User_Mod/Save_Results.f90
The problem was in the User_Mod_Save_Results functions.  It had
two possible exits (returns) from the function, without restoring
the problem name to its original value.
> Issue #30 (.vtu .cgns save are broken)

- Sources/Process/Update_Boundary_Values.f90
Wall distance was missing in the formula. It is fixed now.
> There was a bug in calculation of Twall for zeta-f model.

- Sources/Process/Compute_Energy.f90
- Tests/Rans/Channel_Re_Tau_590/Rsm/control
I re-introduced turbulent heat fluxes which I previously removed believing they were part of cross diffusion treatment from old time steps :-(
Now there is a special section for them, starting with:
```
!---------------------------!                                                 
!                           !                                                 
!   Turbulent heat fluxes   !                                                 
!                           !                                                 
!---------------------------!                                                 
if(turbulence_model .eq. RSM_HANJALIC_JAKIRLIC .or.  &                        
turbulence_model .eq. RSM_MANCEAU_HANJALIC) then                           
```
> Missing heat fluxes

- Sources/Process/Allocate_Variables.f90
- Sources/Process/Main_Pro.f90
- Sources/Process/Read_Physical.f90
- Sources/Process/Turbulence/Calculate_Heat_Flux.f90
- Sources/Process/Turbulence/Calculate_Vis_T_Rsm.f90
- Sources/Process/Turbulence/Compute_Stresses.f90
- Sources/Process/Turbulence/Constants_Hanjalic_Jakirlic.f90
- Sources/Process/Turbulence/Constants_Manceau_Hanjalic.f90
- Sources/Process/Turbulence/Rans_Mod.f90
- Sources/Process/Turbulence/Sources_Rsm_Hanjalic_Jakirlic.f90
- Sources/Process/Turbulence/Time_And_Length_Scale.f90
- Sources/Process/makefile_explicit_dependencies
I made changes in Hanjalic Jakirlic model based on an experience gained during computation of flow around cylinder with heat transfer. It proved that Eps_tot is making a lot of problems and does not influence results much. It is deleted and only Eps is used.
c_theta in GGDH is introduced and defined in Constants_Hanjalic_Jakirlic and Constants_Manceau_Hanjalic.
Constants_Reynolds_Stress is renamed to Constants_Manceau_Hanjalic.
I suggest to implement these changes before the pull planned for buoyancy model.
> Some changes related to Hanjalic Jakirlic RSM model

- Sources/Process/Turbulence/Allocate.f90
[Process/Turbulence/Allocate.f90](https://github.com/DelNov/T-Flows/blob/93b9f061b5ec14c3e96bba6a3de5d99d34c31f0e/Sources/Process/Turbulence/Allocate.f90#L231) function did not have an allocation block for the first moments statistics (**u % mean**, **v % mean**,**w % mean**, **p % mean**) for RSM models.
> statistics in RSM models causes a crash

- Sources/Process/Turbulence/Calculate_Vis_T_K_Eps.f90
- Sources/Process/Turbulence/Calculate_Vis_T_K_Eps_Zeta_F.f90
- Sources/Process/Turbulence/Source_Eps_K_Eps.f90
- Sources/Process/Turbulence/Source_Eps_K_Eps_Zeta_F.f90
- Sources/Process/Turbulence/Source_Kin_K_Eps.f90
- Sources/Process/Turbulence/Source_Kin_K_Eps_Zeta_F.f90
- Sources/Process/Turbulence/Time_And_Length_Scale.f90
I defined a limiter for hydraulic roughness z_o so if z_o is very small or close to zero, the standard log law for smooth wall will be imposed. 
There was one bug discovered by Massimo in Kin source for k-eps model. It is corrected.
> Some improvements for rough walls model and one bug corrected

- Sources/Process/Load_Boundary_Conditions.f90
- Sources/Process/Load_Physical_Properties.f90
There are a change in Load_Boundary_Condition compared to previous versions of the files:
In Load_Boundary_Conditions.f90 i made as a default to supply all three coordinates for inflow that is defined in plain, X Y Z. Previously just two coordinates were needed but then I noticed that the order in which they were listed in control file was important which makes this way of defining the boundary stiff (Y Z will work but Z Y will not work). In addition, we did not take into a count plain that is not aligned with Cartesian coordinates.  By taking all three coordinates we solved all of these issues.
> Load_Boundary_Conditions.f90 and Load_Physical_Properties.f90 are added.

- Sources/Process/Load_Physical_Properties.f90
- Sources/Process/Save_Vtu_Results.f90
There was a bug in Save_Vtu_Results.f90 which in case of hybrid model writes name of variable TurbulentHeatFluxX twice in the file which then causes crashing of Paraview. It is fixed now.
> Bug in Save_Vtu_Results.f90

- Sources/Shared/Grid_Mod/Sort_Cells_Smart.f90
The so-called Smart Cell Sorting proved out to be not so
smart after all.  Namelly, there was no guarantuess that
it won't result in c2 < c1 at certain faces.  With this
commit it was fixed.
> Fixed cell sorting.

- Sources/Divide/Allocate_Additional.f90
- Sources/Divide/Create_Buffers_And_Save.f90
- Sources/Divide/Main_Div.f90
- Sources/Shared/Div_Mod.f90
- Sources/Shared/Grid_Mod/Decompose.f90
- Sources/Shared/Grid_Mod/Save_Cns.f90
- Sources/Shared/Grid_Mod/Save_Geo.f90
- Sources/Shared/Save_Grid_Mod/Vtu/Save_Vtu_Links.f90
Dear Egor,
Div_Mod is an artifact of the past - of the days when T-Flows was still called T-Rex, was written in Fortran 77 and used modules to store global variables :-(
Hence, I am looking for a way to eliminate Div_Mod, variable by variable.  With this pull request I am eliminating one of them - buf_pos.
Cheers,
Bojan
> Eliminated redundant array "buf_pos" from Div_Mod.

- Sources/Process/Load_Boundary_Conditions.f90
- Sources/Process/Turb_Mod/Allocate.f90
Muhamed found a problem with allocation of memory for inlet profiles in Load_Boundary_Conditions.  My humble me found out that production due to buoyancy doesn't get allocated for k_eps, for if someone decides to use this model (which beginners have a tendency to do), the program crashes.
With this pull request we take care of them both.
> Two little fixes

- Sources/Process/User_Mod/Interface_Exchange.f90
Dear Egor, 
with this commit and pull request I keep the default `User_Mod/Interface_Exchange.f90` to exchange temperature information at the interface (for as I argued that will most likely be needed by users) but I get out of the function in case `heat_transfer` flag is not set to `.true.`
Alternatively, we can leave this function empty, and always compile `T-Flows` with `CASE_DIR` option engaged if someone wants to run problems with two domains.  I am OK with both solutions.
> Avoids exchanging temperature information for problems without heat transfer.

- Sources/Process/Save_Results_Mod/Vtu/Save_Results.f90
Dear Hamo,
This fixes the problem when Paraview crashes if results in boundary cells are opened for parallel runs.
I tested it on Ubuntu 18 with OpenMPI and works.
Cheers,
Bojan
> Fixed crash when results in boundary cells are opened with Paraview

- Sources/Divide/Save_Subdomains.f90
- Sources/Process/Backup_Mod/Load.f90
- Sources/Process/Backup_Mod/Read_Bnd.f90
- Sources/Process/Backup_Mod/Read_Cell_Bnd.f90
- Sources/Process/Backup_Mod/Read_Variable.f90
- Sources/Process/Backup_Mod/Save.f90
- Sources/Process/Backup_Mod/Write_Bnd.f90
- Sources/Process/Backup_Mod/Write_Cell_Bnd.f90
- Sources/Process/Backup_Mod/Write_Variable.f90
- Sources/Shared/Comm_Mod_Par.f90
- Sources/Shared/Comm_Mod_Seq.f90
- Sources/Shared/Grid_Mod/Form_Maps.f90
At certain point, program started to give wrong values at
bounary cells after restart.  Unfortnatelly, this has to
do with the way boundary cells are sorted in Divide/Save_Subdomains.f90
procedure, since it impacts the way maps for backup are created.
> Fixed wrong boundary values after restart.

- Sources/Process/Turb_Mod/Vis_T_K_Eps.f90
- Tests/Rans/Impinging_Jet_2d_Distant_Re_23000/User_Mod/Impinging_Jet_Profiles.f90
- Tests/Rans/Pipe_Re_Tau_550/User_Mod/Save_Results.f90
I imposed Durbin's limiter on VISt calculated by k-eps model. This helps in some cases to avoid divergence and stabilize computations. In addition, a few minor bugs in user functions have been fixed.
> Vis t improved for keps

- Tests/Les/Rayleigh_Benard_Convection_Ra_10e09/generate.scr
- Tests/test_build.sh
Dear Hamo,
This is a very small modification.  Our test_build.sh script used to create files of the form: test_build.date.time.... which is neat, but one doesn't know which branch was tested which is quite an important piece of information.  This pull requests takes care of it.  Script test_build.sh now creates a file of the form: test_branch_name_of_the_branch.date.time.
Also, while performing tests, I realized that generate.scr got missing from Les/Rayleigh_Benard_Convection_Ra_10e09 so I simply added it back.
On branch main
new file:   Les/Rayleigh_Benard_Convection_Ra_10e09/generate.scr
modified:   test_build.sh
> Script test_build.sh adds branch name to log file
