DelNov/T-Flows

Sources/Process/Calculate_Face_Geometry.f90, Sources/Process/Flow_Mod.f90, Sources/Process/Update_Boundary_Values.f90, Sources/Shared/Grid_Mod.f90, Sources/Shared/Grid_Mod/Allocate_Faces.f90
I think the function needs revision; for example epsilon at boundaries, heat flux dimensions.
=> Fixed issue #5 (Update_Boundary_Values).

Sources/Process/Main_Pro.f90, Sources/Process/Read_Backup_Variable.f90, Sources/Process/Save_Backup.f90
Indeed, in the function "Read_Backup_Variable", fluxes were not read.
=> Fixed issue #3 (no fluxes saved to backup files)

Tests/test_build.sh
only one file was changed - test_build.sh
=> Added save_now / exit_now tests in test_build.sh

Sources/Process/Compute_Temperature.f90, Sources/Process/Initialize_Variables.f90, Sources/Process/Main_Pro.f90, Sources/Process/Turbulence/Calculate_Sgs.f90, Sources/Process/Turbulence/Source_Hanjalic_Jakirlic.f90, Sources/Process/Update_Boundary_Values.f90, Sources/Process/User_Mod/Compute_Scalar.f90
sqrt(  grid % sx(s)*grid % sx(s)  &
+ grid % sy(s)*grid % sy(s)  &
+ grid % sz(s)*grid % sz(s))
with this:
grid % s(s)
Also, aligned programming lines in Source_Hanjalic_Jakirlic.f90 and brought
a number of variable names to standards we adopted.
=> Issue #28: changed frequent occurence of:

Sources/Shared/Sort_Real_Carry_Int_Heapsort.f90
1)Merge_Blocks.f90 -> Merge_Nodes_New.f90
Merge_Nodes.f90 -> Merge_Nodes_Old.f90
2) output in Merge_Nodes_New.f90 is fixed now
3) arrays in Sort_Real_Carry_Int_Heapsort.f90 start from 1
=> Minor changes to a commit with latest cgns improvements:

Sources/Process/makefile
Two minor things: changed the case for variable "value" to upper and also added option CGNS_HDF5 in info message of the makefile.
=> Changed the case for variable "value" to upper.

Sources/Convert/Main_Con.f90, Sources/Divide/Create_Buffers_And_Save.f90, Sources/Divide/Create_Maps.f90, Sources/Shared/Save_Vtu_Cells.f90, Sources/Shared/Save_Vtu_Faces.f90
This is the fix to erroneous wall distance after Divide.
=> Fixing wall distance

Sources/Process/Control_Mod/Physics/Mass_Flow_Rates.f90
I fixed the issue with erroneous mass flux in simulations with periodic boundaries.
=> Fixed issue #67!

Sources/Process/Allocate_Variables.f90, Sources/Process/Turbulence/Calculate_Heat_Flux.f90, Sources/Process/Turbulence/Rans_Mod.f90
(It is much easir to debug and mantain this way)
=> Ordered turbulent variable allocation model by model.

Sources/Process/Save_Cgns_Results.f90, Sources/Process/Turbulence/Calculate_Sgs.f90
Filter width (`lf`) was not initialized inside a loop for LES_DYNAMIC model.
=> Fixed issue #70 (Les/Pipe_Re_Tau_180)

Sources/Convert/Load_Neu.f90
(It was actually wrong version of Gambit)
=> Fixed .neu files from Windows.

Sources/Process/Initialize_Variables.f90, Sources/Process/Turbulence/Time_And_Length_Scale.f90
=> Time and lenght scales subroutine is corrected, bulk inflow velocity is fixed

Sources/Process/makefile_explicit_dependencies
I run makefile_explicit_dependencies  script that fixed the problem in compilation. Please check why automatic merge is not possible.
=> Problem with compiling is solved. 

Sources/Process/Main_Pro.f90
Yesterday I merged development_branch to release_branch by mistake, and with this pull request am removing the line 'use Swarm_Mod' from the `Main_Pro.f90`
=> Issue #122: Removed "use Swarm_Mod" statement.

Sources/Process/Load_Boundary_Conditions.f90, Sources/Shared/Comm_Mod/Sequential/Start.f90, Sources/Shared/Grid_Mod/Calculate_Wall_Distance.f90, Sources/Shared/Grid_Mod/Load_Geo.f90, Sources/Shared/Grid_Mod/Save_Geo.f90
Now the programs compute wall distance in boundary cells too.  I believe this should be good for boundary condition which specifies "distance from the wall", abbreviated `dw` in the control file.
=> Niceno issue 124

Sources/Process/Main_Pro.f90, Sources/Process/Turbulence/Source_Zeta_K_Eps_Zeta_F.f90, Tests/Les/Channel_Re_Tau_180/User_Mod/Save_Results.f90, Tests/Les/Pipe_Re_Tau_180/User_Mod/Save_Results.f90
Source file for zeta was missing pointer for grid so grid % vol was making an error. No idea how this appear, could be my mistake. 
This is all.
=> Pointer for grid was missing and grid % vol causing an error.

Tests/test_build.sh
In the issue #133 Bojan fairly noticed that save_exit_now test case behaved somehow incorrectly.
In particular, string
`save_exit_now_test was successful`
has never appeared.
It turned out that test relied on the output in stdout rather than in **$LOG_FILE**.
It is fixed now.
Moreover,
scenario which this test case reproduces is now more intricate and accurate than before.
I also made output for this test case more verbose.
=> Updated test_build.sh: process_save_exit_now_test

Sources/Process/Compute_Scalar.f90, Sources/Process/Main_Pro.f90
Two little fixes from the last push
=> Fixed a couple of issues with scalar.

Sources/Convert/makefile, Sources/Shared/Grid_Mod/Calculate_Wall_Distance.f90
This commit is already in the development branch, 
but Muhamed asked me to apply it to the release branch now.
This commit was created by one command:
git cherry-pick [e8aaacb3a79e07922cc37b0abd0a6383b32d1736](https://github.com/DelNov/T-Flows/commit/e8aaacb3a79e07922cc37b0abd0a6383b32d1736?diff=split)
=> Convert feature - openmp for Grid_Mod_Calculate_Wall_Distance (requested by Muhamed)

Sources/Process/Save_Cgns_Results.f90, Sources/Process/Save_Vtu_Results.f90
This pull request follows #151 by Muhamed (@mhadziabdic) and applies T-Flows code standards
=> Edited the latest commit to code standards

Sources/Process/Turbulence/Source_Eps_K_Eps_Zeta_F.f90, Sources/Process/Turbulence/Source_Kin_K_Eps_Zeta_F.f90, Sources/Process/Turbulence/Time_And_Length_Scale.f90
Dear all,
I made some implementation in compound wall treatment which effect results for channel flow when first y+ is in buffer region. I tested implementation on impinging jet and backstep flow and both tests were satisfactory.
=> Compound wall treatment is improved. 

Sources/Process/Backup_Mod/Write_Face.f90, Sources/Process/Convective_Outflow.f90, Sources/Process/Field_Mod/Calculate_Fluxes.f90, Sources/Process/Main_Pro.f90, Sources/Process/Turb_Mod/Init.f90
Dear Egor,
I discovered two errors: one in writing backup files, the other in computation of bulk velocities.
Please have a look and accept the fixes if they are fine.
Cheers,
Bojan
=> Fix bulk velocity and backup

Sources/Process/Save_Results_Mod/Vtu/Save_Results.f90, Sources/Process/Turb_Mod/Allocate.f90, Sources/Shared/Grid_Mod/Load_Cns.f90
Hamo, 
I fixed the issue you raised, but couldn't move the `Turb_Mod_Calculate_Deltas` for some reason :-(
We can try it later.
=> Fixing issue 186

Sources/Process/makefile
I had to re-introduce it before giving the code to some students.
=> Makefile prints messages again.

Sources/Process/Field_Mod.f90, Sources/Process/Field_Mod/Schmidt_Number.f90, Sources/Process/Turb_Mod.f90, Sources/Process/Turb_Mod/Allocate.f90, Sources/Process/Turb_Mod/Src_Kin_K_Eps_Zeta_F.f90, Sources/Process/Turb_Mod/Vis_T_K_Eps_Zeta_F.f90, Sources/Process/Update_Boundary_Values.f90
I added wall function for user defined scalar.
=> Development branch local

Sources/Convert/Allocate_Memory.f90, Sources/Convert/Find_Parents.f90, Sources/Convert/Load_Msh.f90, Sources/Convert/Load_Neu.f90, Sources/Convert/Main_Con.f90
Dear Hamo,
With this pull request, I am trying to introduce a (much) simpler version of the subroutine `Find_Parents` used in Convert.  
Kind regards,
Bojan
=> Simplified the algorithm in Find_Parents big time!

Sources/Process/Update_Boundary_Values.f90
both heating and cooling processes can be considered.
=> Heat flux is caluclated as it is, without abs function, so

Sources/Process/Update_Boundary_Values.f90
=> Some lines that are obsolete are removed. They make the program crashes

Tests/Laminar/Accuracy_Test/Channel_Re_2000/User_Mod/Save_Results.f90
On branch bojan_fix_accuracy_test
modified:   Tests/Laminar/Accuracy_Test/Channel_Re_2000/User_Mod/Save_Results.f90
=> BUG FIX: The .1d file should be opened for writing

Tests/test_build.sh
On branch bojan_fix_accuracy_test
modified:   test_build.sh
=> Yet another fix in the test_build.sh

Sources/Process/Main_Pro.f90, Sources/Process/Results_Mod.f90, Sources/Process/Results_Mod/Time_To_Save.f90, Sources/Process/Solver_Mod/Bicg.f90, Sources/Process/Solver_Mod/Cg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Bicg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Cg.f90, Sources/Process/Vof_Mod/Utilities/Calculate_Grad_Matrix_With_Front.f90, Tests/Vof/Sucking/User_Mod/End_Of_Compute_Energy.f90
Hi Hamo,
I did some additional small fixes in solvers.  In some places comments were outlining the number of used variables from `Work_Mod` wrong, and in `Cg.f90` in particular, the fix you did on `Bicg.f90` and `Cgs.f90` for calling buffer refresh at the right place was not applied at all.
All of these changes do not affect functionality in any way since they are in comments and the solver which is fixed is never actually called because it resides in directory `Solvers_Mod/Normalized_Solvers`.
=> Bojan small fixes in solvers

Sources/Process/Compute_Energy.f90, Sources/Process/Compute_Momentum.f90, Sources/Process/Compute_Scalar.f90, Sources/Process/Front_Mod/Mark_Cells_And_Faces.f90, Sources/Process/Solver_Mod/Bicg.f90, Sources/Process/Solver_Mod/Dimensional_Solvers/Bicg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Bicg.f90, Sources/Process/Turb_Mod/Compute_Stress.f90, Sources/Process/Turb_Mod/Compute_Variable.f90, Tests/Vof/Sucking/Sucking_Problem.f90, Tests/Vof/Sucking/User_Mod/Check_Inside_Box.f90, Tests/Vof/Sucking/User_Mod/End_Of_Compute_Energy.f90, Tests/Vof/Sucking/User_Mod/Initialize_Variables.f90, Tests/Vof/Sucking/User_Mod/Vof_Initialization_Box.f90, Tests/Vof/Sucking/User_Mod/Vof_Interface_Box.f90
Initialization of advection and cross diffusion sources was missing in all subroutines which discretize and solve partial differential equations.  This is why I ask to merge this branch.
Once I submitted it, I realized the pull request also entails some changes in comments which correct the info on using the Work_Mod (which, although comments, are important) as well as some subtle changes in a test case for boiling I am conducting which can't possibly influence any other part of the code.
=> Bojan fixed missing initialization

Sources/Process/Solver_Mod/Bicg.f90, Sources/Process/Solver_Mod/Cg.f90, Sources/Process/Solver_Mod/Cgs.f90, Sources/Process/Solver_Mod/Dimensional_Solvers/Cg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Bicg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Cg.f90, Sources/Process/Solver_Mod/Normalized_Solvers/Cgs.f90
which fixes the issue with slightly unpredictable
behaviour.
On branch bojan_correct_soler_normalisation
modified:   Process/Solver_Mod/Bicg.f90
modified:   Process/Solver_Mod/Cg.f90
modified:   Process/Solver_Mod/Cgs.f90
modified:   Process/Solver_Mod/Dimensional_Solvers/Cg.f90
modified:   Process/Solver_Mod/Normalized_Solvers/Bicg.f90
modified:   Process/Solver_Mod/Normalized_Solvers/Cg.f90
modified:   Process/Solver_Mod/Normalized_Solvers/Cgs.f90
=> Implemented different kind of solver normalization

Tests/Laminar/Membrane/2_Domains/User_Mod/Beginning_Of_Iteration.f90, Tests/Laminar/Membrane/2_Domains/User_Mod/Initialize_Variables.f90, Tests/Laminar/Membrane/2_Domains/User_Mod/Interface_Exchange.f90
Hi Hamo,
I made a little update on the case "Membrane/2_Domains".  It is just in the user files, no big deal.  When you approve, feel free to remove this branch.
On branch bojan_updated_case_membrane
modified:   Tests/Laminar/Membrane/2_Domains/User_Mod/Beginning_Of_Iteration.f90
modified:   Tests/Laminar/Membrane/2_Domains/User_Mod/Initialize_Variables.f90
modified:   Tests/Laminar/Membrane/2_Domains/User_Mod/Interface_Exchange.f90
=> Correctly prints averaged values from the membrane

Sources/Convert/Load_Gmsh.f90
On branch bojan_updated_case_membrane
modified:   Load_Gmsh.f90
=> Made Convert more robust.

readme.md
(Just checking if branch protection rule works)
=> Deleted a trailing empty line
